name: Run Tests Before Push
on:
  push:
    branches:
      - main
  pull_request:
   branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.6"  # Fixed whitespace issue

      - name: Install dependencies
        run: pip install -r requirements.txt && pip list  # Ensure dependencies are installed

      - name: Debug Current Directory
        run: pwd && ls -R

      - name: Print Environment Variables
        run: env

      - name: Run test and capture output
        id: run_test
        run: |
          output=$(python src/confidence_score_test.py test/cv.txt test/Job_Description1.txt test/cover_letter.txt)
          echo "Raw Output: $output"
          echo "OUTPUT=$output" >> $GITHUB_ENV  # Store the output in GitHub Actions env

      - name: Check if output is greater than 50
        run: |
          output=${{ env.OUTPUT }}  # Retrieve stored output
          echo "Processed Output: $output"
          if [[ "$output" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then  # Ensure output is a number
            output_int=$(python -c "print(int(float('$output')))")
            echo "Converted Output: $output_int"
            if (( output_int > 50 )); then
              echo "Test passed: Output ($output_int) is greater than 50"
            else
              echo "Test failed: Output ($output_int) is not greater than 50"
              exit 1
            fi
          else
            echo "Test failed: Output is not a valid number ($output)"
            exit 1
          fi
