# name: Run Tests Before Push

# on:
#   push:
#     branches:
#       - main  # Change this to your branch if needed
#   pull_request:

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.9"  # Change this based on your Python version

#       - name: Install dependencies
#         run: pip install -r test/requirements.txt  # Add this if you have dependencies

#       - name: Run test
#         run: python src/confidence_score_test.py test/cv.txt test/Job Description1.txt test/cover_letter.txt > output.txt

#       - name: Check if output is greater than 50
#         run: |
#           output=$(cat output.txt)
#           echo $output
#           if [ "$output" -gt 50 ]; then
#             echo "✅ Test passed: Output ($output) is greater than 50"
#           else
#             echo "❌ Test failed: Output ($output) is not greater than 50"
#             exit 1
#           fi

name: Run Tests Before Push

on:
  push:
    branches:
      - main  # Change this to your branch if needed
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Change this based on your Python version

      - name: Install dependencies
        run: pip install -r test/requirements.txt  # Add this if you have dependencies

      - name: Run test and capture output
        id: run_test
        run: |
          output=$(python src/confidence_score_test.py test/cv.txt "test/Job Description1.txt" test/cover_letter.txt)
          echo "Raw Output: $output"
          echo "TEST_OUTPUT=$output" >> $GITHUB_ENV  # Store output in environment variable

      - name: Check if output is greater than 50
        run: |
          output="$TEST_OUTPUT"  # Retrieve stored output
          echo "Processed Output: $output"
          if [[ "$output" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then  # Ensure output is a number
            output_float=$(python -c "print(float('$output'))")  # Convert to float
            echo "Converted Output: $output_float"
            if (( $(echo "$output_float > 50" | bc -l) )); then
              echo "✅ Test passed: Output ($output_float) is greater than 50"
            else
              echo "❌ Test failed: Output ($output_float) is not greater than 50"
              exit 1
            fi
          else
            echo "❌ Test failed: Output is not a valid number ($output)"
            exit 1
          fi
